### ISSUE TITLE
Upgrade to using PMD 6.14.0

### ISSUE THREAD

**Issue by tjoneslo** [jensgerdes/sonar-pmd#117]
I've just encountered https://github.com/pmd/pmd/issues/1532 which is listed as fixed in 6.14.0 so having this fix for the PMD sonar plugin would be very nice. 

Thanks.

**Comment by takeseem** [comment]
#163

**Comment by vhuynh4thalesgroup** [comment]
Is there any plan to fix this issue ? 
see : https://github.com/pmd/pmd/issues/1532

It would be very valuable :)
Thanks a lot

**Comment by jensgerdes** [comment]
PMD will be bumped to 6.29 or 6.30 within the next weeks. Consequently, I expect this issue to be fixed.

**Comment by vhuynh4thalesgroup** [comment]
Do you know when the associated release will be available ?

**Comment by jensgerdes** [comment]
Hi @vhuynh4thalesgroup 

There are still one or two things I would like to improve prior performing the release. Once that is done - probably within the next 4-5 days, I will inform SonarSource about the new release. There will be a 14 days test period. So, it will be available in the SonarQube market place at Mid of January. 
You can of course still manually update once I have release sonar-pmd using the JARs on Maven Central or [Github](https://github.com/jensgerdes/sonar-pmd/releases).
