### ISSUE TITLE
Upgrade PMD from 6.13.0 to 6.28.0, for support JDK 15

### ISSUE THREAD

**Issue by mohanaraosv** [jensgerdes/sonar-pmd#216]
Could you please upgrade the PMD dependency version in order to support Java15?

There is already PR for this upgrades Please merge them https://github.com/jensgerdes/sonar-pmd/pull/213

```
  Caused by: java.lang.IllegalArgumentException: Unsupported Java version for PMD: 15
      at org.sonar.plugins.pmd.PmdTemplate.languageVersion (PmdTemplate.java:83)
      at org.sonar.plugins.pmd.PmdTemplate.create (PmdTemplate.java:72)
      at org.sonar.plugins.pmd.PmdExecutor.createPmdTemplate (PmdExecutor.java:159)
      at org.sonar.plugins.pmd.PmdExecutor.executePmd (PmdExecutor.java:97)
      at org.sonar.plugins.pmd.PmdExecutor.execute (PmdExecutor.java:80)
      at org.sonar.plugins.pmd.PmdSensor.execute (PmdSensor.java:71)

```

**Comment by jborgers** [comment]
There is PR #220 already. Please merge, thanks!

**Comment by jborgers** [comment]
It is not just bumping to the new version, there is also an incompatible API change in pmd. I solved it in my fork: https://github.com/jborgers/sonar-pmd

**Comment by jborgers** [comment]
I created a PR: #228

**Comment by jborgers** [comment]
Note that the documentation still needs updates concerning supported versions.

**Comment by jborgers** [comment]
Hi Jens,

When will you create a new release?

Kind regards, met vriendelijke groet,

Jeroen Borgers

drs. Jeroen Borgers
Principal Consultant
jPinpoint Performance Services, jpinpoint com, The Netherlands.
Mobile: +31(0)6-30128951, e-mail: jborgers at jpinpoint com


Op zo 13 dec. 2020 om 23:40 schreef Jens Gerdes <notifications@github.com>:

**Comment by jensgerdes** [comment]
I started a bigger refactoring along with the previous changes - but I'll postpone them to create the release first. 👍

**Comment by jborgers** [comment]
That release first would be great.

In my experience refactorings can get quite hairy :-)

cheers


Op ma 11 jan. 2021 om 11:47 schreef Jens Gerdes <notifications@github.com>:

**Comment by jensgerdes** [comment]
I have release [3.3.0](https://github.com/jensgerdes/sonar-pmd/releases/tag/3.3.0) yesterday evening. I would very much appreciate if you could beta-test this release. Simply replace the existing sonar-pmd-plugin-3.2.1.jar with this one in your SonarQube plugin directory.

The availability in the SonarQube marketplace usually takes some time.

**Comment by jborgers** [comment]
Hi Jens,

Great, thanks!

I replaced my own built snapshot jar we use as a temporary fix, with your
3.3.0 and it works!

Kind regards, met vriendelijke groet,

Jeroen Borgers

drs. Jeroen Borgers
Principal Consultant
jPinpoint Performance Services, jpinpoint com, The Netherlands.
Mobile: +31(0)6-30128951, e-mail: jborgers at jpinpoint com


Op di 12 jan. 2021 om 08:48 schreef Jens Gerdes <notifications@github.com>:

**Comment by jensgerdes** [comment]
Graag gedaan. ;-)

**Comment by jborgers** [comment]
:-) Je praat Nederlands?

groet, jeroen

Op di 12 jan. 2021 om 11:03 schreef Jens Gerdes <notifications@github.com>:

**Comment by jborgers** [comment]
Hi Jens,

There seem to be issues on Windows with 3.3.0-snapshot like:

[ERROR] Failed to execute goal
org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
(default-cli) on project xxx-service: Illegal character in opaque part at
index 5:
file:\C:\a\14\s\src\main\java\nl\company\department\service\domain\MdcCodes.java
-> [Help 1]

Does that ring a bell?

Kind regards, met vriendelijke groet,

Jeroen Borgers

drs. Jeroen Borgers
Principal Consultant
jPinpoint Performance Services, jpinpoint com, The Netherlands.
Mobile: +31(0)6-30128951, e-mail: jborgers at jpinpoint com


Op di 12 jan. 2021 om 14:43 schreef Jeroen Borgers <jborgers@jpinpoint.com>:

**Comment by jensgerdes** [comment]
Damn. :-/

Yes, I have an idea of what causes this issue. In the plugin I correlate Sonar input files with the files analyzed by PMD - via URI. It sounds like this is not correctly implemented for Windows path structure.

I'll look into this this evening.

**Comment by jborgers** [comment]
Okay that would be great. I remember I changed something in that area
because of pmd or sonar api changes.
Do you have a windows machine at hand to test? I don't.

Op di 12 jan. 2021 17:33 schreef Jens Gerdes <notifications@github.com>:

**Comment by jensgerdes** [comment]
Fortunately yes :)

**Comment by jborgers** [comment]
Good. Any progress?
Our Windows developers are not happy :-(

cheers


Op wo 13 jan. 2021 om 08:51 schreef Jens Gerdes <notifications@github.com>:

**Comment by jensgerdes** [comment]
Did you have a chance to check if my proposed bugfix works for your Windows-colleagues?

**Comment by jborgers** [comment]
Unfortunately not. I passed the Windows testing on to my colleagues and
apparently there are some issues in their process. Will keep you posted.

Cheers, Jeroen

Op vr 15 jan. 2021 om 12:32 schreef Jens Gerdes <notifications@github.com>:

**Comment by jborgers** [comment]
Hi Jens,

The Windows testers reported that the opaque issue is solved!

Cheers, Jeroen

Op vr 15 jan. 2021 om 16:10 schreef Jeroen Borgers <jborgers@jpinpoint.com>:

**Comment by jensgerdes** [comment]
Cool, thank you for getting back to me.
I will merge the PR then.
