### ISSUE TITLE
Add support of Java 11+ version

### ISSUE THREAD

**Issue by xpinjection** [jensgerdes/sonar-pmd#235]
At the moment in PmdTemplate.java only Java versions up to 11 are configured. At the same time, JavaLanguageModule in the PMD actually supports Java versions up to 15:

https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java

**Comment by jensgerdes** [comment]
Hi @xpinjection,

with [this](https://github.com/jensgerdes/sonar-pmd/pull/229/commits/631071a2680a5b70c0abde4edb08dc02c3681d85) commit, I added support for Java up until Java 15.
The changes are already in master and waiting to be released.

**Comment by xpinjection** [comment]
Great, thanks!
