### ISSUE TITLE
PMD plugin does not work with sonar 6.2

### ISSUE THREAD

**Issue by Nandakumar1982** [jensgerdes/sonar-pmd#35]
This is what I get upon clicking Quality profiles > Java (Sonar way) > PMD
  
![image](https://cloud.githubusercontent.com/assets/26682786/24328325/27250384-1204-11e7-809a-2194e6a02331.png)

Any suggestions?

**Comment by mechanik0s** [comment]
same problem

**Comment by risinha1** [comment]
what version of PMD plugin should be used to work with sonarqube 6.2

**Comment by Nandakumar1982** [comment]
Gave up. Using both pmd and sonar individually.

Thank you
Nanda

On May 13, 2017 3:15 AM, "risinha1" <notifications@github.com> wrote:

what version of PMD plugin should be used to work with sonarqube 6.2

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SonarQubeCommunity/sonar-pmd/issues/35#issuecomment-301193333>,
or mute the thread

**Comment by timwebster9** [comment]
Hi - allow me to direct you to this discussion:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/sonarqube/PMD%7Csort:relevance/sonarqube/yIr1wYfoQb4/wuDppc1pCAAJ

**Comment by zhangbigflower** [comment]
same problem

**Comment by jensgerdes** [comment]
I'll close this issue as it is probably outdated.
