### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by ganncamp** [jensgerdes/sonar-pmd#50]
@timwebster9 I have someone asking [in the community](https://community.sonarsource.com/t/adopting-sonarqubecommunity-sonar-pmd/2814) to adopt this repo. Are you still interested in maintaining it, or should we transfer ownership to him?

**Comment by jensgerdes** [comment]
The repository has been handed over. Thank you @timwebster9 for your dedicated work within the last years. I'll try to keep up the good work.
