### ISSUE TITLE
how to change the pmd rule type

### ISSUE THREAD

**Issue by koralaro** [jensgerdes/sonar-pmd#54]
i create a new sonar-pmd project ,but the type always is code smell ,how to change it to bug or others

**Comment by jensgerdes** [comment]
Hi @koralaro 

Thank you for your interest in sonar-pmd
The "Type" you are looking for is named "RuleType". See: org.sonar.api.rules.RuleType
To change the type, you have to define it in the XML that holds your rules.
See my example below:
```xml
<rule key="DontCallThreadRun">
  <priority>MAJOR</priority>
  <configKey>rulesets/java/basic.xml/DontCallThreadRun</configKey>
  <type>BUG</type>
</rule>
```
