### ISSUE TITLE
[java] OptimizableToArrayCall message doesn't reflect PMD 6.x changes on this rule

### ISSUE THREAD

**Issue by softdays** [jensgerdes/sonar-pmd#75]
`sonar-pmd Plugin version : 3.1.3`

Since this PMD 6 change: https://github.com/pmd/pmd/pull/775
The plugin detects now the opposite but the message still suggests 

> A call to Collection.toArray can use the Collection's size vs an empty Array of the desired type

instead of something suggesting to use `Collection.toArray(new E[0])` with a zero-sized array.

![image](https://user-images.githubusercontent.com/948293/51083786-0d3cee00-1720-11e9-8011-87f60318241f.png)
![image](https://user-images.githubusercontent.com/948293/51083801-38bfd880-1720-11e9-9cc4-501a995dadcb.png)

**Comment by jensgerdes** [comment]
Hi @softdays 

Thank you for your report. Unfortunately, my private life is quite busy at the moment.
 I'll look into this within the next weeks.
