### ISSUE TITLE
depreciated "Ncss Type Count” (pmd:NcssTypeCount) description suggests a wrong replacement

### ISSUE THREAD

**Issue by florianrosenauer** [jensgerdes/sonar-pmd#78]
The rule "Ncss Type Count” (pmd:NcssTypeCount) has a recommended replacement of "Source files should have a sufficient density of comment lines” (common-java:InsufficientCommentDensity).
This is not a match as the original rule counts statements, and the new rule counts the comment density.

For "Ncss Method Count” (pmd:NcssMethodCount) the replacement rule is “Methods should not have too many lines” (squid:S138).
Following this idea, imho it should be “Files should not have too many lines” (squid:S00104) for "Ncss Type Count pmd:NcssTypeCount", shouldn’t it?

**Comment by jensgerdes** [comment]
Hi @langbogen 

Thank's for your report. I'll check this within the next weeks. Unfortunately, my private life is consuming too much time. ;-)

**Comment by jensgerdes** [comment]
I finally managed to review your request - and yes, I agree: `common-java:InsufficientCommentDensity` is not a correct replacement for `pmd:NcssTypeCount`.
`squid:S00104` is not a good match as well as there can be multiple types within one source file but it is definitely the better choice.
